// Source : https://leetcode.com/problems/find-the-difference/
// Author : Hao Chen
// Date   : 2016-09-08

/*************************************************************************************** 
 * 389. Find the Difference [Easy]
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a 
 * random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 ***************************************************************************************/
// 4 ms, faster than 98.29% of C++, 9.4 MB, less than 11.82% of C++
class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> m;
        for(auto c : s) m[c]++;
        for(auto c : t) {
            m[c]--;
            if (m[c] < 0) return c;
        }
        return '\0';
    }
};

// 0 ms, faster than 100.00% of C++, 9 MB, less than 77.68% of C++
class Solution {
public:
    char findTheDifference(string s, string t) {
        char res = 0;
        for (char c:t) res += c;
        for (char c:s) res -= c;
        return res;
    }
};